<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Stade extends \App\Entity\Stade implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Stade' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Stade' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Stade' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Stade' . "\0" . 'capacite', '' . "\0" . 'App\\Entity\\Stade' . "\0" . 'dateouverture', '' . "\0" . 'App\\Entity\\Stade' . "\0" . 'kiosque', '' . "\0" . 'App\\Entity\\Stade' . "\0" . 'matches', '' . "\0" . 'App\\Entity\\Stade' . "\0" . 'billets'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Stade' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Stade' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Stade' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Stade' . "\0" . 'capacite', '' . "\0" . 'App\\Entity\\Stade' . "\0" . 'dateouverture', '' . "\0" . 'App\\Entity\\Stade' . "\0" . 'kiosque', '' . "\0" . 'App\\Entity\\Stade' . "\0" . 'matches', '' . "\0" . 'App\\Entity\\Stade' . "\0" . 'billets'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Stade $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $Id): \App\Entity\Stade
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$Id]);

        return parent::setId($Id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Stade
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(string $adresse): \App\Entity\Stade
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapacite(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapacite', []);

        return parent::getCapacite();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapacite(int $capacite): \App\Entity\Stade
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapacite', [$capacite]);

        return parent::setCapacite($capacite);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateouverture(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateouverture', []);

        return parent::getDateouverture();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateouverture(\DateTimeInterface $dateouverture): \App\Entity\Stade
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateouverture', [$dateouverture]);

        return parent::setDateouverture($dateouverture);
    }

    /**
     * {@inheritDoc}
     */
    public function getKiosque(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKiosque', []);

        return parent::getKiosque();
    }

    /**
     * {@inheritDoc}
     */
    public function addKiosque(\App\Entity\Kiosque $kiosque): \App\Entity\Stade
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addKiosque', [$kiosque]);

        return parent::addKiosque($kiosque);
    }

    /**
     * {@inheritDoc}
     */
    public function removeKiosque(\App\Entity\Kiosque $kiosque): \App\Entity\Stade
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeKiosque', [$kiosque]);

        return parent::removeKiosque($kiosque);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatches(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatches', []);

        return parent::getMatches();
    }

    /**
     * {@inheritDoc}
     */
    public function addMatch(\App\Entity\Matche $match): \App\Entity\Stade
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMatch', [$match]);

        return parent::addMatch($match);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMatch(\App\Entity\Matche $match): \App\Entity\Stade
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMatch', [$match]);

        return parent::removeMatch($match);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillets(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillets', []);

        return parent::getBillets();
    }

    /**
     * {@inheritDoc}
     */
    public function addBillet(\App\Entity\Billet $billet): \App\Entity\Stade
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBillet', [$billet]);

        return parent::addBillet($billet);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBillet(\App\Entity\Billet $billet): \App\Entity\Stade
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBillet', [$billet]);

        return parent::removeBillet($billet);
    }

}
