<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9QeITcn\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9QeITcn/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9QeITcn.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9QeITcn\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container9QeITcn\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '9QeITcn',
    'container.build_id' => 'dbf8423d',
    'container.build_time' => 1645977215,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9QeITcn');
