<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEfg3NvW\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEfg3NvW/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEfg3NvW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEfg3NvW\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEfg3NvW\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Efg3NvW',
    'container.build_id' => '59a9075d',
    'container.build_time' => 1646690614,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEfg3NvW');
